name: Rodar script baixar-enviar.php

on:
  schedule:
    - cron: '0 8 * * *'  # Executa todos os dias às 5h da manhã (horário de Brasília = UTC-3)
  workflow_dispatch:    # Também permite execução manual

jobs:
  executar:
    runs-on: ubuntu-latest

    env:
      LWEB_USER: ${{ secrets.LWEB_USER }}
      LWEB_PASS: ${{ secrets.LWEB_PASS }}
      HG_USER: ${{ secrets.HG_USER }}
      HG_PASS: ${{ secrets.HG_PASS }}

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Rodar script baixar-enviar.php
        run: php baixar-enviar.php
